# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    open-pull-requests-limit: 10
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    versioning-strategy: 'widen'
  - package-ecosystem: 'github-actions'
    open-pull-requests-limit: 10
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker'
    open-pull-requests-limit: 10
    directory: '/'
    schedule:
      interval: 'weekly'
