import { Neighbour } from './interfaces'
/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface DeviceMetricsEntity {
  airUtilTx?: number
  batteryLevel?: number
  channelUtilization?: number
  createdAt: Date
  id?: number
  nodeId: number
  updatedAt: Date
  uptimeSeconds?: number
  voltage?: number
}
export interface EnvironmentMetricsEntity {
  barometricPressure?: number
  createdAt: Date
  current?: number
  gasResistance?: number
  iaq?: number
  id?: number
  nodeId: number
  relativeHumidity?: number
  temperature?: number
  updatedAt: Date
  voltage?: number
}
export interface MapReportsEntity {
  altitude?: number
  createdAt: Date
  firmwareVersion: string
  hardwareModel: number
  hasDefaultChannel?: boolean
  id?: number
  latitude?: number
  longName: string
  longitude?: number
  modemPreset?: number
  nodeId: number
  numOnlineLocalNodes?: number
  positionPrecision?: number
  region?: number
  role: number
  shortName: string
  updatedAt: Date
}
export interface MigrationsEntity {
  id?: number
  name: string
  timestamp: number
}
export interface NeighbourInfosEntity {
  createdAt: Date
  id?: number
  neighbours: Neighbour[]
  nodeBroadcastIntervalSecs: number
  nodeId: number
  updatedAt: Date
}
export interface NodesEntity {
  airUtilTx?: number
  altitude?: number
  barometricPressure?: number
  batteryLevel?: number
  channelUtilization?: number
  createdAt: Date
  firmwareVersion?: string
  hardwareModel?: number
  hasDefaultChannel?: boolean
  id?: number
  isLicensed?: boolean
  latitude?: number
  longName?: string
  longitude?: number
  modemPreset?: number
  mqttConnectionState?: string
  mqttConnectionStateUpdatedAt?: Date
  neighbourBroadcastIntervalSecs?: number
  neighbours?: Neighbour[]
  neighboursUpdatedAt?: Date
  nodeId: number
  numOnlineLocalNodes?: number
  positionPrecision?: number
  positionUpdatedAt?: Date
  region?: number
  relativeHumidity?: number
  role?: number
  shortName?: string
  temperature?: number
  updatedAt: Date
  uptimeSeconds?: number
  voltage?: number
}
export interface PositionsEntity {
  altitude?: number
  channel?: number
  channelId?: string
  createdAt: Date
  from: number
  gatewayId?: number
  id?: number
  latitude?: number
  longitude?: number
  nodeId: number
  packetId?: number
  to: number
  updatedAt: Date
}
export interface PowerMetricsEntity {
  ch1Current?: number
  ch1Voltage?: number
  ch2Current?: number
  ch2Voltage?: number
  ch3Current?: number
  ch3Voltage?: number
  createdAt: Date
  id?: number
  nodeId: number
  updatedAt: Date
}
export interface ServiceEnvelopesEntity {
  channelId: string
  createdAt: Date
  from: number
  gatewayId?: number
  id?: number
  mqttTopic: string
  protobuf: Buffer
  to: number
  updatedAt: Date
}
export interface TextMessagesEntity {
  channel?: number
  channelId?: string
  createdAt: Date
  from: number
  gatewayId?: number
  hopLimit?: number
  id?: number
  packetId?: number
  rxRssi?: number
  rxSnr?: number
  rxTime?: number
  text: string
  to: number
  updatedAt: Date
  wantResponse: boolean
}
export interface TraceroutesEntity {
  channel?: number
  channelId?: string
  createdAt: Date
  from: number
  gatewayId?: number
  id?: number
  packetId?: number
  route: any // eslint-disable-line @typescript-eslint/no-explicit-any
  to: number
  updatedAt: Date
  wantResponse: boolean
}
export interface WaypointsEntity {
  channel: number
  channelId: string
  createdAt: Date
  description?: string
  expire?: number
  from: number
  gatewayId?: number
  icon?: number
  id?: number
  latitude: number
  lockedTo?: number
  longitude: number
  name?: string
  packetId: number
  to: number
  updatedAt: Date
  waypointId: number
}
